apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: couchdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
