apiVersion: v1
kind: Service
metadata:
  name: sdlc-server-{{ .Values.project.slug }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sdlc-server
    app.kubernetes.io/instance: {{ .Values.project.slug }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sdlc-server
    app.kubernetes.io/instance: {{ .Values.project.slug }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
